Create settings side bar
mugna-tech/randomzr pull request #12
Opened 2021-11-09 11:05 UTC by mphernaez

2021-11-11 09:34 UTC, jlorencelim requested changes
Remove any variables or comments that are not used

2021-11-11 09:36 UTC, jlorencelim requested changes

2021-11-11 09:36 UTC, jlorencelim commented on components/Layout/NavBar/index.js
> +                  <Link href="/roulette">
These link seems to be repetitive. Maybe store the values in a dictionary then just loop over

2021-11-11 10:02 UTC, diomari requested changes
Added some comments

2021-11-11 10:02 UTC, diomari commented on package.json
> +    "party-js": "^2.1.2",
Is this used?

2021-11-12 03:12 UTC, mphernaez commented on components/Layout/Background/index.js
> +const Background = () => <>{/* <Red /> */}</>;
This page is still todo, just forgot to add comment, will do it now

2021-11-12 03:13 UTC, mphernaez commented on package.json
> +    "party-js": "^2.1.2",
Still working on adding this to the winner modal

2021-11-12 06:06 UTC, jlorencelim requested changes

2021-11-12 06:06 UTC, jlorencelim commented on pages/roulette/index.js
> +    const t = [...updatedTheme];
Let's not use of single letter variable names. Make them descriptive as possible

2021-11-12 06:06 UTC, jlorencelim commented on components/Settings/index.js
> +  const onChangeTheme = (t) => {
Let's not use single letter variable names.

2021-11-12 06:06 UTC, jlorencelim commented on components/Settings/index.js
> +  const onUpdateNames = (e) => {
Let's not use single letter variable names. Apply to all others bellow

2021-11-12 08:56 UTC, mphernaez commented on components/Roulette/RouletteWheel/index.js
>          // clearInterval(interval);
These are still to do, I commented it out because the weren't working yet

2021-11-12 08:57 UTC, mphernaez commented on components/Roulette/RouletteWheel/index.js
> +  // let lastSoundAngle;
part of the roulette sound effect function, I haven't finished it yet

2021-11-12 09:18 UTC, mphernaez commented on components/Settings/index.js
> +  const onUpdateNumbers = () => {
I can't find a way to map an `int` value, is there a way to do this?

2021-11-12 10:34 UTC, jlorencelim requested changes

2021-11-12 10:34 UTC, jlorencelim commented on components/Settings/index.js
> +  const onUpdateNumbers = () => {
You can use `lodash` library's `range` function

2021-11-12 15:22 UTC, diomari requested changes
Just a minor comment

2021-11-12 15:22 UTC, diomari commented on components/Roulette/OuterWheel/styles.js
> +  position: absolute;
remove duplicate properties

2021-11-15 06:08 UTC, jlorencelim approved these changes

2021-11-15 06:44 UTC, diomari approved these changes
lgtm

2021-11-15 09:16 UTC, merged