Roulette
mugna-tech/randomzr pull request #13
Opened 2021-11-15 09:22 UTC by mphernaez

Created change logo function, and sound function, and  general bug fixes

2021-11-15 09:29 UTC, jlorencelim requested changes

2021-11-15 09:29 UTC, jlorencelim commented on components/Roulette/Wheel/index.js
> +      option.length > 0 ? option.map((line, index) => ctx.fillText(line, -ctx.measureText(line).width / 2, index *  fontSize )) : option.map((line, index) => ctx.fillText(line, -ctx.measureText(line)
This line is too long and hard to read. Better place the 2 option maps in separate variable before doing a ternary operator

2021-11-15 10:33 UTC, mphernaez commented on components/Roulette/Wheel/index.js
> +      option.length > 0 ? option.map((line, index) => ctx.fillText(line, -ctx.measureText(line).width / 2, index *  fontSize )) : option.map((line, index) => ctx.fillText(line, -ctx.measureText(line)
Is it okay if I just rearrange it, to make it more readable like this?:
```
 option.length > 0
        ? option.map((line, index) =>
            ctx.fillText(
              line,
              -ctx.measureText(line).width / 2,
              index * fontSize
            )
          )
        : option.map((line) =>
            ctx.fillText(line, -ctx.measureText(line).width / 2, fontSize / 2.7)
          );
```

2021-11-15 10:34 UTC, jlorencelim commented on components/Roulette/Wheel/index.js
> +      option.length > 0 ? option.map((line, index) => ctx.fillText(line, -ctx.measureText(line).width / 2, index *  fontSize )) : option.map((line, index) => ctx.fillText(line, -ctx.measureText(line)
That is also fine 👍

2021-11-15 10:36 UTC, mphernaez commented on components/Roulette/Wheel/index.js
> +      option.length > 0 ? option.map((line, index) => ctx.fillText(line, -ctx.measureText(line).width / 2, index *  fontSize )) : option.map((line, index) => ctx.fillText(line, -ctx.measureText(line)
okay! I'll just add some comments too, to make it easier to read.
Thanks!

2021-11-15 12:48 UTC, diomari requested changes
Minor changes

2021-11-15 12:48 UTC, diomari commented on pages/roulette/index.js
> +              onClick={() => setWinnersModalIsOpen(!winnersModalIsOpen)}
For consistency use your created function `toggleWinnersModal` or decide wether to remove it and use anonymous function instead

2021-11-15 12:48 UTC, diomari commented on components/Roulette/RouletteWheel/index.js
> +import { includes, last } from 'lodash';
Remove if not used.

2021-11-16 04:49 UTC, jlorencelim approved these changes

2021-11-16 09:06 UTC, jlorencelim requested changes

2021-11-16 09:06 UTC, jlorencelim commented on components/Roulette/RouletteWheel/index.js
> +        lastTick = currentAngle; // added -3 to make tick more accurate since the interval tends to skip some numbers
Maybe remove the comment since the `- 3` is already removed here

2021-11-16 09:06 UTC, jlorencelim commented on components/Roulette/RouletteWheel/styles.js
> +          props.spinngingTime >= 30000
Is this a typo? `spinngingTime`

2021-11-16 09:27 UTC, jlorencelim approved these changes

2021-11-16 11:21 UTC, mugnatech approved these changes

2021-11-17 03:06 UTC, merged