Roulette
mugna-tech/randomzr pull request #16
Opened 2021-11-18 12:15 UTC by mphernaez

Create unit tests for roulette

2021-11-18 12:38 UTC, jlorencelim commented on components/Roulette/OuterWheel/index.js
> +        ></CenterImage>
Since there's no component added in the `CenterImage`, no need to close it by using this `</CenterImage>`. You can just do it like this:
```
<CenterImage 
    data-testid="centerImage"
    image={image.image}
/>

2021-11-22 02:01 UTC, diomari requested changes
Add testing on event clicks (button click, if they click the roulette etc). Refer to this https://reactjs.org/docs/testing-recipes.html#events just mock the onChange function and make sure it is called upon click.

2021-11-22 13:45 UTC, jlorencelim requested changes

2021-11-22 13:45 UTC, jlorencelim commented on components/Settings/__test__/settings.test.js
> +it('renders data entrie/s', () => {
Is this a typo

2021-11-22 13:45 UTC, jlorencelim commented on utils/__tests__/utils.test.js
> +it('converst rgb to hex', () => {
Type here

2021-11-23 13:10 UTC, diomari commented on components/Settings/__test__/settings.test.js
> +    expect(mockOnClick).toHaveBeenCalled();
Any reason for this timeout?

2021-11-24 06:56 UTC, mphernaez commented on components/Settings/__test__/settings.test.js
> +    expect(mockOnClick).toHaveBeenCalled();
I added a timeout because if I just automatically run `expect` after the `fireEvent`, the `useState` function would not have finished rerendering the page before the it

2021-11-24 08:31 UTC, jlorencelim approved these changes

2021-11-24 08:33 UTC, diomari approved these changes

2021-11-25 05:08 UTC, merged